### PR TITLE
Fix the wrong version info, close #19

### LINKED ISSUE #19: The version info is wrong
Using the lastest pipreqs:

    $ pipreqs --version
    xstat 0.1

which should be `0.2.8`.

In this [line](https://github.com/bndr/pipreqs/blob/master/pipreqs/pipreqs.py#L173), you write down that the version info is `xstat 0.1`, while you bump pipreqs version only in setup.py

### PR DESCRIPTION
**Pull request by lord63**
Maintain the version info only in `pipreqs/__init__.py`.

### CODE REVIEW

**Comment by bndr** [comment]
Thanks!

**Comment by lord63** [comment]
By the way, when I ran `python setup.py test`, it failed.

```
running test
running egg_info
writing requirements to pipreqs.egg-info/requires.txt
writing pipreqs.egg-info/PKG-INFO
writing top-level names to pipreqs.egg-info/top_level.txt
writing dependency_links to pipreqs.egg-info/dependency_links.txt
writing entry points to pipreqs.egg-info/entry_points.txt
reading manifest file 'pipreqs.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching 'stdlib' under directory 'docs'
warning: no files found matching 'mapping' under directory 'docs'
writing manifest file 'pipreqs.egg-info/SOURCES.txt'
running build_ext
test_get_all_imports (tests.test_pipreqs.TestPipreqs) ... ok
test_get_import_name_without_alias (tests.test_pipreqs.TestPipreqs) ... ok
test_get_imports_info (tests.test_pipreqs.TestPipreqs) ... ok
test_get_use_local_only (tests.test_pipreqs.TestPipreqs) ... FAIL
test_init (tests.test_pipreqs.TestPipreqs) ... ok
test_init_local_only (tests.test_pipreqs.TestPipreqs) ... FAIL
test_init_overwrite (tests.test_pipreqs.TestPipreqs) ... ok
test_init_savepath (tests.test_pipreqs.TestPipreqs) ... ok

======================================================================
FAIL: test_get_use_local_only (tests.test_pipreqs.TestPipreqs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lord63/code/0/pipreqs/tests/test_pipreqs.py", line 55, in test_get_use_local_only
    self.assertTrue(item['name'].lower() in self.local)
AssertionError: False is not true

======================================================================
FAIL: test_init_local_only (tests.test_pipreqs.TestPipreqs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lord63/code/0/pipreqs/tests/test_pipreqs.py", line 74, in test_init_local_only
    self.assertTrue(item[0].lower() in self.local)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 8 tests in 48.333s

FAILED (failures=2)
```

when I try this commit fe71b900759284d0e684f511177008f0a031cc5e(Version v0.2.8), failed again, but it is OK with CI.

So this PR fails on my PC but OK with CI, just a note.(You merged the PR so fast that I don't have time to write down those)

**Comment by bndr** [comment]
Yeah there are problems with the local_imports testing when virtualenv already has other packages installed.
I usually test it like so:
```
mkvirtualenv newvirtualenv
make test
```

**Comment by lord63** [comment]
I set up a new virtualenv environment, but failed again:

      $ virtualenv bbb
      $ . bbb/bin/activate
      $ make test


```
python setup.py test
running test
running egg_info
writing requirements to pipreqs.egg-info/requires.txt
writing pipreqs.egg-info/PKG-INFO
writing top-level names to pipreqs.egg-info/top_level.txt
writing dependency_links to pipreqs.egg-info/dependency_links.txt
writing entry points to pipreqs.egg-info/entry_points.txt
reading manifest file 'pipreqs.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching 'stdlib' under directory 'docs'
warning: no files found matching 'mapping' under directory 'docs'
writing manifest file 'pipreqs.egg-info/SOURCES.txt'
running build_ext
test_get_all_imports (tests.test_pipreqs.TestPipreqs) ... ok
test_get_import_name_without_alias (tests.test_pipreqs.TestPipreqs) ... ok
test_get_imports_info (tests.test_pipreqs.TestPipreqs) ... ok
test_get_use_local_only (tests.test_pipreqs.TestPipreqs) ... FAIL
test_init (tests.test_pipreqs.TestPipreqs) ... ok
test_init_local_only (tests.test_pipreqs.TestPipreqs) ... FAIL
test_init_overwrite (tests.test_pipreqs.TestPipreqs) ... ok
test_init_savepath (tests.test_pipreqs.TestPipreqs) ... ok

======================================================================
FAIL: test_get_use_local_only (tests.test_pipreqs.TestPipreqs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lord63/code/0/pipreqs/tests/test_pipreqs.py", line 55, in test_get_use_local_only
    self.assertTrue(item['name'].lower() in self.local)
AssertionError: False is not true

======================================================================
FAIL: test_init_local_only (tests.test_pipreqs.TestPipreqs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lord63/code/0/pipreqs/tests/test_pipreqs.py", line 74, in test_init_local_only
    self.assertTrue(item[0].lower() in self.local)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 8 tests in 66.900s

FAILED (failures=2)
```


I don't want that my patch would break the tests, but if it works well on your side, just ignore it.

**Pull request merged**
