### PR TITLE
CI: Add Python 3.10 and 3.11, update actions

### PR DESCRIPTION
**Pull request by willianrocha**
A bit of CI maintenance:
- Add Python 3.10 and 3.11 runs, and update the PyPy run to PyPy 3.9
- Update the used actions to the latest versions
- Also run on pushes, when manually triggered (workflow_dispatch)

I could not rebase and reuse the old PR https://github.com/bndr/pipreqs/pull/334

### CODE REVIEW

**Comment by fredgrub** [comment]
You should mention the PR (and the author) in the commit. According to Alan's suggestion in https://github.com/bndr/pipreqs/pull/396#issuecomment-1742992660.

**Comment by alan-barzilay** [comment]
https://docs.python.org/3.12/whatsnew/3.12.html

add python 3.12 please

**Comment by alan-barzilay** [comment]
actually, please use all supported pythonv ersions and remove unsupported ones

https://devguide.python.org/versions/

**Review by alan-barzilay — CHANGES_REQUESTED** [review]
alongside the changes requested, please also add in the commit message a mention to the updated action version

**Pull request closed without merging**
