### PR TITLE
CI: Add Python 3.10 and 3.11, update actions, run weekly

### PR DESCRIPTION
**Pull request by EwoutH**
A bit of CI maintenance:
- Add Python 3.10 and 3.11 runs, and update the PyPy run to PyPy 3.9
- Update the used actions to the latest versions
- Also run on pushes, when manually triggered (`workflow_dispatch`) and once a week (Monday at 06:00 UTC)

Also updates the `tox.ini` with Python 3.10 and 3.11 environments.

### CODE REVIEW

**Comment by EwoutH** [comment]
Hi @alan-barzilay! Could you review this PR?

**Comment by alan-barzilay** [comment]
@EwoutH  for some reason the CI isnt showing for me either so I can't seem to find a way to approve it. I have been away from the project for some time while focusing on finishing my thesis so maybe I' m forgetting something obvious, sorry about that.

Looking at your pr everything seems fine so i have no problem with merging it since it is so simple, the only thing you could change is to also drop 3.6 since it is no longer supported.

Let me know if you want to change that or if you have an inkling about whats wrong with the CI, otherwise I will probably just merge the PR as is

**Comment by EwoutH** [comment]
Thanks for getting back. That's weird, [it's running](https://github.com/EwoutH/pipreqs/actions/runs/3372912732) on my fork.

**Comment by EwoutH** [comment]
I created a separate PR for requiring Python 3.7: #339. Once that is merged I will update this PR and we will see how it goes.

**Comment by alan-barzilay** [comment]
implemented in #406 (except for run weekly, which we opted to not implement)

**Pull request closed without merging**
