### PR TITLE
Handling multiple imports in the same line when using aliases

### PR DESCRIPTION
**Pull request by tiagofmcosta**
* Fix for #13.
* Fixed some indentation issues where tabs were being used.
* Added tests for the new method `get_import_name_without_alias`

### CODE REVIEW

**Comment by bndr** [comment]
Can you rebase from current master? I can't automatically merge this pull request.

**Comment by tiagofmcosta** [comment]
Yes, I'll do it in a few moments.

**Comment by tiagofmcosta** [comment]
I think it's done, can you check please?

**Comment by bndr** [comment]
Hey, I can't merge your branch, too many conflicts, can you create new branch from current master and recommit your changes there? You can reopen new pull request after that.

**Comment by tiagofmcosta** [comment]
Sure, no problem. Sorry for the issues, I should've just done that in the first place. Thanks.

**Pull request closed without merging**
